@startuml
'https://plantuml.com/sequence-diagram

boundary RequestHandler
database CockroachDB

-> RequestHandler: GET /products
alt Request invalid
    <-- RequestHandler: <b>[400]
end

RequestHandler -> CockroachDB ++ : Get products
alt Read failure
    RequestHandler <-- CockroachDB: null
    <-- RequestHandler : <b>[500]
end
RequestHandler <- CockroachDB -- : Product[]
<- RequestHandler : <b>[200]

@enduml