Post Product.puml@startuml
'https://plantuml.com/sequence-diagram

boundary RequestHandler
database CockroachDB

-> RequestHandler: POST /tester
alt Request invalid
    <-- RequestHandler: <b>[400]
end

RequestHandler -> CockroachDB ++ : Save tester
alt Save failure
    RequestHandler <-- CockroachDB: <b>failure
    <-- RequestHandler : <b>[500]
end
RequestHandler <- CockroachDB -- : <b>success
<- RequestHandler : <b>[200]

@enduml